export const alertRed = '#fa4352'
export const alertPending = '#ff9800'
export const dark = '#1d2028'
export const fog = '#d8d8d8'
export const graphite = '#767676'
export const grey = '#999999'
export const identity = '#41ccb4'
export const lightGrey = '#f9f9f9'
export const positiveGreen = '#96d071'
export const primary =
  process.env.REACT_APP_BASE_URL === 'prod' ? '#27B88F' : '#4b84ff'
export const primaryDark =
  process.env.REACT_APP_BASE_URL === 'prod' ? '#1a785c' : '#2666ff'
export const transparent = 'transparent'
export const white = '#ffffff'
